# Site settings
title: "ADSI Summer Workshop: Algorithmic Foundations of Learning and Control"
email: ajwagen@uw.edu
url:  "https://ajwagen.github.io/"
description: "A workshop on learning and control at the University of Washington"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#444444'
  links: '#e8e3d3'

# Footer settings
footer: # Ariel Rokem, UW eScience Institute

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
  #  url: https://twitter.com/neurohackademy
  #- title: facebook
  #  url:
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
  #  url: http://bitbucket.org/jekyll
  #- title: github
  #  url: https://github.com/neurohackademy

# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-cayman